# Symiosis Configuration File
# Uncomment and modify the options below to configure the application

# ============================
# TOP-LEVEL ESSENTIAL SETTINGS
# ============================

# Default: ~/Documents/Notes (or equivalent on your system)
notes_directory = "{DEFAULT_NOTES_DIR}"

# Format: modifier keys + key (e.g., "Ctrl+Shift+N", "Cmd+Space", "Alt+F1")
# Supported modifiers: Ctrl, Alt, Shift, Cmd (macOS), Super (Linux)
global_shortcut = "Ctrl+Shift+N"

# =====================
# GENERAL CONFIGURATION
# =====================

[general]
# Future extensible core settings
# This section is reserved for general application behavior settings

# =======================
# INTERFACE CONFIGURATION
# =======================

[interface]
# UI theme for the application interface
# Options: "gruvbox-dark", "one-dark",
ui_theme = "gruvbox-dark"

# Font family for the UI
font_family = "Inter, sans-serif"

# Font size for the UI (in pixels)
font_size = 14

# Font family for the editor
editor_font_family = "JetBrains Mono, Consolas, monospace"

# Font size for the editor (in pixels)
editor_font_size = 14

# Markdown rendering theme for note content
# Options: "light", "dark", "dark_dimmed", "auto"
markdown_render_theme = "dark_dimmed"

# Window appearance and behavior
default_width = 1200
default_height = 800
center_on_startup = true
remember_size = true
remember_position = true
always_on_top = false

# ====================
# EDITOR CONFIGURATION
# ====================

[editor]
# Editor mode: "basic", "vim", "emacs"
mode = "basic"

# Editor theme (separate from UI theme)
# Options: "gruvbox-dark", "one-dark"
theme = "gruvbox-dark"

# Enable word wrapping
word_wrap = true

# Tab size in spaces
tab_size = 2

# Show line numbers
show_line_numbers = true

# ==================
# KEYBOARD SHORTCUTS
# ==================

[shortcuts]
# All keyboard shortcuts in one unified section
create_note = "Ctrl+Enter"
rename_note = "Ctrl+m"
delete_note = "Ctrl+x"
save_and_exit = "Ctrl+s"
open_external = "Ctrl+o"
open_folder = "Ctrl+f"
refresh_cache = "Ctrl+r"
scroll_up = "Ctrl+u"
scroll_down = "Ctrl+d"
vim_up = "Ctrl+k"
vim_down = "Ctrl+j"
navigate_previous = "Ctrl+p"
navigate_next = "Ctrl+n"
open_settings = "Meta+,"

# ===========
# PREFERENCES
# ===========

[preferences]
# Maximum number of search results to display
max_search_results = 100
